### ISSUE TITLE
Centrar el título de la página.

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-mariviru#3]
Parece que nos hemos quedado cortas con el alto

- Hay que hacer que el body, o una etiqueta madre de header y main ocupe todo el alto (vh mola ;)
- Hay que hacer que esa etiqueta madre tenga un `display:flex`, con la dirección adecuada,
- ¿Y como hacemos que el main crezca? Como te has marcado un display: flex muy chachi en la etiqueta madre, vamos a aprovechar que main es un item flex y a jugar con eso.
A por ello!

**Comment by mariviru** [comment]
Este me ha costado un poquillo pero creo que al final lo he hecho bien.
