### ISSUE TITLE
Apañar detalles

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-mariviru#6]
Buen trabajo!!!!
You got it woman!

¿Le damos un par de pinceladas finales y ponemos broche?

Si vas agrandando la pantalla desde la versión móvil hasta la tablet, el logo y el menú se ponen en línea, parece que solo están uno debajo del otro en tamaños muy pequeños por qué no tienen espacio para estar alado.

Algo similar ocurre con las palabras del título principal.

A ver si se te ocurren ideas para que se queden donde deben ;)

**Comment by mariviru** [comment]
Arreglado lo del menú. En el título principal no veo muy claro lo que quieres decir, yo veo que se va adaptando, lo único que le he subido un poco el flex-basis al class .titulo de 50% a 70% para que tenga más espacio pero no sé si es eso lo que querías decir.

**Comment by nasivuela** [comment]
Si no recuerdo mal cada palabra del título estaba en una línea en ambas versiones. Si utilizas porcentajes, en pantallas con mayores anchos las palabras no saltan, ya que 50% equivale a muchos píxeles y hay espacio para que toda la frase se quede en una linea. Igual otro tipo de unidad hace el apaño. Si no te funciona con flex-basis, dale una probada a width o max- width ;)

**Comment by mariviru** [comment]
Ah ok! no me había fijado en eso, habría jurado que en la versión tablet se expandía la frase. Vale ahora lo arreglo ;)

**Comment by mariviru** [comment]
Creo que ya está, he probado de varias formas y me parece que así queda bien. Lo he comprobado hasta en pantallas de 4000px.

**Comment by nasivuela** [comment]
![](https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif)
